#ifndef SASS_C_VERSION_H
#define SASS_C_VERSION_H

#ifndef LIBSASS_VERSION
#define LIBSASS_VERSION "[NA]"
#endif

#ifndef LIBSASS_LANGUAGE_VERSION
#define LIBSASS_LANGUAGE_VERSION "3.5"
#endif

#endif
