#ifndef SASS_COLOR_MAPS_H
#define SASS_COLOR_MAPS_H

#include <map>
#include "ast.hpp"

namespace Sass {

  struct map_cmp_str
  {
    bool operator()(char const *a, char const *b) const
    {
      return std::strcmp(a, b) < 0;
    }
  };

  namespace ColorNames
  {
    extern const char aliceblue[];
    extern const char antiquewhite[];
    extern const char cyan[];
    extern const char aqua[];
    extern const char aquamarine[];
    extern const char azure[];
    extern const char beige[];
    extern const char bisque[];
    extern const char black[];
    extern const char blanchedalmond[];
    extern const char blue[];
    extern const char blueviolet[];
    extern const char brown[];
    extern const char burlywood[];
    extern const char cadetblue[];
    extern const char chartreuse[];
    extern const char chocolate[];
    extern const char coral[];
    extern const char cornflowerblue[];
    extern const char cornsilk[];
    extern const char crimson[];
    extern const char darkblue[];
    extern const char darkcyan[];
    extern const char darkgoldenrod[];
    extern const char darkgray[];
    extern const char darkgrey[];
    extern const char darkgreen[];
    extern const char darkkhaki[];
    extern const char darkmagenta[];
    extern const char darkolivegreen[];
    extern const char darkorange[];
    extern const char darkorchid[];
    extern const char darkred[];
    extern const char darksalmon[];
    extern const char darkseagreen[];
    extern const char darkslateblue[];
    extern const char darkslategray[];
    extern const char darkslategrey[];
    extern const char darkturquoise[];
    extern const char darkviolet[];
    extern const char deeppink[];
    extern const char deepskyblue[];
    extern const char dimgray[];
    extern const char dimgrey[];
    extern const char dodgerblue[];
    extern const char firebrick[];
    extern const char floralwhite[];
    extern const char forestgreen[];
    extern const char magenta[];
    extern const char fuchsia[];
    extern const char gainsboro[];
    extern const char ghostwhite[];
    extern const char gold[];
    extern const char goldenrod[];
    extern const char gray[];
    extern const char grey[];
    extern const char green[];
    extern const char greenyellow[];
    extern const char honeydew[];
    extern const char hotpink[];
    extern const char indianred[];
    extern const char indigo[];
    extern const char ivory[];
    extern const char khaki[];
    extern const char lavender[];
    extern const char lavenderblush[];
    extern const char lawngreen[];
    extern const char lemonchiffon[];
    extern const char lightblue[];
    extern const char lightcoral[];
    extern const char lightcyan[];
    extern const char lightgoldenrodyellow[];
    extern const char lightgray[];
    extern const char lightgrey[];
    extern const char lightgreen[];
    extern const char lightpink[];
    extern const char lightsalmon[];
    extern const char lightseagreen[];
    extern const char lightskyblue[];
    extern const char lightslategray[];
    extern const char lightslategrey[];
    extern const char lightsteelblue[];
    extern const char lightyellow[];
    extern const char lime[];
    extern const char limegreen[];
    extern const char linen[];
    extern const char maroon[];
    extern const char mediumaquamarine[];
    extern const char mediumblue[];
    extern const char mediumorchid[];
    extern const char mediumpurple[];
    extern const char mediumseagreen[];
    extern const char mediumslateblue[];
    extern const char mediumspringgreen[];
    extern const char mediumturquoise[];
    extern const char mediumvioletred[];
    extern const char midnightblue[];
    extern const char mintcream[];
    extern const char mistyrose[];
    extern const char moccasin[];
    extern const char navajowhite[];
    extern const char navy[];
    extern const char oldlace[];
    extern const char olive[];
    extern const char olivedrab[];
    extern const char orange[];
    extern const char orangered[];
    extern const char orchid[];
    extern const char palegoldenrod[];
    extern const char palegreen[];
    extern const char paleturquoise[];
    extern const char palevioletred[];
    extern const char papayawhip[];
    extern const char peachpuff[];
    extern const char peru[];
    extern const char pink[];
    extern const char plum[];
    extern const char powderblue[];
    extern const char purple[];
    extern const char red[];
    extern const char rosybrown[];
    extern const char royalblue[];
    extern const char saddlebrown[];
    extern const char salmon[];
    extern const char sandybrown[];
    extern const char seagreen[];
    extern const char seashell[];
    extern const char sienna[];
    extern const char silver[];
    extern const char skyblue[];
    extern const char slateblue[];
    extern const char slategray[];
    extern const char slategrey[];
    extern const char snow[];
    extern const char springgreen[];
    extern const char steelblue[];
    extern const char tan[];
    extern const char teal[];
    extern const char thistle[];
    extern const char tomato[];
    extern const char turquoise[];
    extern const char violet[];
    extern const char wheat[];
    extern const char white[];
    extern const char whitesmoke[];
    extern const char yellow[];
    extern const char yellowgreen[];
    extern const char rebeccapurple[];
    extern const char transparent[];
  }

  namespace Colors {
    extern const Color_Ref aliceblue;
    extern const Color_Ref antiquewhite;
    extern const Color_Ref cyan;
    extern const Color_Ref aqua;
    extern const Color_Ref aquamarine;
    extern const Color_Ref azure;
    extern const Color_Ref beige;
    extern const Color_Ref bisque;
    extern const Color_Ref black;
    extern const Color_Ref blanchedalmond;
    extern const Color_Ref blue;
    extern const Color_Ref blueviolet;
    extern const Color_Ref brown;
    extern const Color_Ref burlywood;
    extern const Color_Ref cadetblue;
    extern const Color_Ref chartreuse;
    extern const Color_Ref chocolate;
    extern const Color_Ref coral;
    extern const Color_Ref cornflowerblue;
    extern const Color_Ref cornsilk;
    extern const Color_Ref crimson;
    extern const Color_Ref darkblue;
    extern const Color_Ref darkcyan;
    extern const Color_Ref darkgoldenrod;
    extern const Color_Ref darkgray;
    extern const Color_Ref darkgrey;
    extern const Color_Ref darkgreen;
    extern const Color_Ref darkkhaki;
    extern const Color_Ref darkmagenta;
    extern const Color_Ref darkolivegreen;
    extern const Color_Ref darkorange;
    extern const Color_Ref darkorchid;
    extern const Color_Ref darkred;
    extern const Color_Ref darksalmon;
    extern const Color_Ref darkseagreen;
    extern const Color_Ref darkslateblue;
    extern const Color_Ref darkslategray;
    extern const Color_Ref darkslategrey;
    extern const Color_Ref darkturquoise;
    extern const Color_Ref darkviolet;
    extern const Color_Ref deeppink;
    extern const Color_Ref deepskyblue;
    extern const Color_Ref dimgray;
    extern const Color_Ref dimgrey;
    extern const Color_Ref dodgerblue;
    extern const Color_Ref firebrick;
    extern const Color_Ref floralwhite;
    extern const Color_Ref forestgreen;
    extern const Color_Ref magenta;
    extern const Color_Ref fuchsia;
    extern const Color_Ref gainsboro;
    extern const Color_Ref ghostwhite;
    extern const Color_Ref gold;
    extern const Color_Ref goldenrod;
    extern const Color_Ref gray;
    extern const Color_Ref grey;
    extern const Color_Ref green;
    extern const Color_Ref greenyellow;
    extern const Color_Ref honeydew;
    extern const Color_Ref hotpink;
    extern const Color_Ref indianred;
    extern const Color_Ref indigo;
    extern const Color_Ref ivory;
    extern const Color_Ref khaki;
    extern const Color_Ref lavender;
    extern const Color_Ref lavenderblush;
    extern const Color_Ref lawngreen;
    extern const Color_Ref lemonchiffon;
    extern const Color_Ref lightblue;
    extern const Color_Ref lightcoral;
    extern const Color_Ref lightcyan;
    extern const Color_Ref lightgoldenrodyellow;
    extern const Color_Ref lightgray;
    extern const Color_Ref lightgrey;
    extern const Color_Ref lightgreen;
    extern const Color_Ref lightpink;
    extern const Color_Ref lightsalmon;
    extern const Color_Ref lightseagreen;
    extern const Color_Ref lightskyblue;
    extern const Color_Ref lightslategray;
    extern const Color_Ref lightslategrey;
    extern const Color_Ref lightsteelblue;
    extern const Color_Ref lightyellow;
    extern const Color_Ref lime;
    extern const Color_Ref limegreen;
    extern const Color_Ref linen;
    extern const Color_Ref maroon;
    extern const Color_Ref mediumaquamarine;
    extern const Color_Ref mediumblue;
    extern const Color_Ref mediumorchid;
    extern const Color_Ref mediumpurple;
    extern const Color_Ref mediumseagreen;
    extern const Color_Ref mediumslateblue;
    extern const Color_Ref mediumspringgreen;
    extern const Color_Ref mediumturquoise;
    extern const Color_Ref mediumvioletred;
    extern const Color_Ref midnightblue;
    extern const Color_Ref mintcream;
    extern const Color_Ref mistyrose;
    extern const Color_Ref moccasin;
    extern const Color_Ref navajowhite;
    extern const Color_Ref navy;
    extern const Color_Ref oldlace;
    extern const Color_Ref olive;
    extern const Color_Ref olivedrab;
    extern const Color_Ref orange;
    extern const Color_Ref orangered;
    extern const Color_Ref orchid;
    extern const Color_Ref palegoldenrod;
    extern const Color_Ref palegreen;
    extern const Color_Ref paleturquoise;
    extern const Color_Ref palevioletred;
    extern const Color_Ref papayawhip;
    extern const Color_Ref peachpuff;
    extern const Color_Ref peru;
    extern const Color_Ref pink;
    extern const Color_Ref plum;
    extern const Color_Ref powderblue;
    extern const Color_Ref purple;
    extern const Color_Ref red;
    extern const Color_Ref rosybrown;
    extern const Color_Ref royalblue;
    extern const Color_Ref saddlebrown;
    extern const Color_Ref salmon;
    extern const Color_Ref sandybrown;
    extern const Color_Ref seagreen;
    extern const Color_Ref seashell;
    extern const Color_Ref sienna;
    extern const Color_Ref silver;
    extern const Color_Ref skyblue;
    extern const Color_Ref slateblue;
    extern const Color_Ref slategray;
    extern const Color_Ref slategrey;
    extern const Color_Ref snow;
    extern const Color_Ref springgreen;
    extern const Color_Ref steelblue;
    extern const Color_Ref tan;
    extern const Color_Ref teal;
    extern const Color_Ref thistle;
    extern const Color_Ref tomato;
    extern const Color_Ref turquoise;
    extern const Color_Ref violet;
    extern const Color_Ref wheat;
    extern const Color_Ref white;
    extern const Color_Ref whitesmoke;
    extern const Color_Ref yellow;
    extern const Color_Ref yellowgreen;
    extern const Color_Ref rebeccapurple;
    extern const Color_Ref transparent;
  }

  extern const std::map<const int, const char*> colors_to_names;
  extern const std::map<const char*, Color_Ptr_Const, map_cmp_str> names_to_colors;

  extern Color_Ptr_Const name_to_color(const char*);
  extern Color_Ptr_Const name_to_color(const std::string&);
  extern const char* color_to_name(const int);
  extern const char* color_to_name(const Color_Ref&);
  extern const char* color_to_name(const double);

}

#endif
